name               = "programming"
main               = "src/index.js"
compatibility_date = "2026-03-22"

[assets]
directory          = "./public"
binding            = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first   = ["/post", "/post.html"]

[vars]
MICROCMS_SERVICE_DOMAIN = "coderoute90"
MICROCMS_ENDPOINT = "coderoute90"